#!/usr/bin/env bash
set -euo pipefail

PR_NUMBER="${GITHUB_EVENT_NUMBER:-}"
if [[ -z "${PR_NUMBER}" ]]; then
  PR_NUMBER=$(jq -r '.pull_request.number // empty' "${GITHUB_EVENT_PATH}" 2>/dev/null || true)
fi

if [[ -z "${PR_NUMBER}" ]]; then
  echo "::warning::Could not determine PR number, skipping comment"
  exit 0
fi

REPO="${GITHUB_REPOSITORY}"
MARKER="<!-- kube-events-action -->"

# Build comment body
if [[ "${HAS_WARNINGS}" == "true" ]]; then
  TITLE="### :warning: Cluster Warnings Detected (${WARNING_COUNT} warnings)"
else
  TITLE="### :white_check_mark: No Cluster Warnings"
fi

# Format result as collapsible section
FORMATTED_RESULT=""
if [[ -n "${EVENTS_RESULT}" ]]; then
  FORMATTED_RESULT="<details>
<summary>Event Details</summary>

\`\`\`
${EVENTS_RESULT}
\`\`\`

</details>"
fi

BODY="${MARKER}
${TITLE}

${FORMATTED_RESULT}
---
*Generated by [kube-events-action](https://github.com/somaz94/kube-events-action)*"

# Check for existing comment and update or create
EXISTING_COMMENT_ID=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" 2>/dev/null | head -1 || true)

if [[ -n "${EXISTING_COMMENT_ID}" ]]; then
  echo "Updating existing comment ${EXISTING_COMMENT_ID}"
  gh api "repos/${REPO}/issues/comments/${EXISTING_COMMENT_ID}" \
    -X PATCH \
    -f body="${BODY}" > /dev/null
else
  echo "Creating new comment on PR #${PR_NUMBER}"
  gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
    -f body="${BODY}" > /dev/null
fi

echo "::notice::PR comment posted successfully"
